version: 2

builds:
  - binary: mehshell
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - format: tar.gz
    name_template: "mehshell_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

brews:
  - repository:
      owner: blackflame007
      name: homebrew-tap
    homepage: https://github.com/blackflame007/mehshell
    description: "Fast, parallelized zsh prompt engine written in Go"
    license: MIT
    install: |
      bin.install "mehshell"

changelog:
  sort: asc
